### ISSUE TITLE
When pool connection is not heath, the connection.close() sometime will raise an exception.

### ISSUE THREAD

**Issue by cnkailyn** [neo4j/neo4j-python-driver#1056]
Backgroud:
I got an issue raised from neo4j:
this this the exception logs:
![image](https://github.com/neo4j/neo4j-python-driver/assets/34443073/f411b391-cce3-4b34-96c1-e9ed631b45a3)
![image](https://github.com/neo4j/neo4j-python-driver/assets/34443073/6ed66a16-8882-4ff6-8a9d-a06192b93d95)

Then I checked the source code here:
![image](https://github.com/neo4j/neo4j-python-driver/assets/34443073/847fcfe1-5175-4a29-bff7-88f3f86ce6cc)

The direct issue is the connection is not health, maybe the TCP have already closed, but we still call connection.close(), then it raise that 'RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x56126bcdf100>; the handler is closed'. 

there should add a try for connection.close() or add some conditions like:
`
if not conncetion.tcp.closed:
    conncetion.close()
`

**Comment by robsdedude** [comment]
Hi and thanks for the bug report. It'd be a great help for me if you could share some extra information with me so that I can understand the problem in more detail:
 * What operating system are you using?
 * What event loop are you running? I'm suspecting that this is run using `uvloop` and not `asynio`.
 * Please share the *full* stack trace of the error (ideally as text, and not a screenshot, but better a screenshot than nothing)
 * If you can reproduce the error, I'd be very happy to see driver debug logs so that I can see what the connection in question was doing before the failure. Here are the API docs on how to enable the debug logs: https://neo4j.com/docs/api/python-driver/current/api.html#logging

**Comment by robsdedude** [comment]
Hello again @cnkailyn :wave: 

Can you please share the requested information so that I can start investigating?

**Comment by robsdedude** [comment]
I'll close the issue now.

I've not heard back in over a month and I suspect that this is rather a bug in `uvloop` that claims to be a drop-in replacement for `asyncio` but fails to throw the same exceptions under the same conditions.

Please feel free to keep commenting if you have further questions. Should this turn out to be a bug in the driver, I'm happy to re-open the issue.
