### ISSUE TITLE
connection_timeout not honoured?

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#203]
I ran into a problem with a docker compose setup with a python app and a neo4j 3.3 server. The app container can start up before the Neo server is ready. 
I get this exception:
```
neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host='neo', port=7687)
```
So I wanted to use the connection_timeout to a largish number (like 10) to allow for this. 
```
    driver = GraphDatabase.driver( "bolt://neo:7687", connection_timeout=10)
```
However it seems it doesn't do anything. I still get the exception and the driver call does not take noticeably longer. 
If I manually restart the app everything is OK.

Also I noticed that you can pass any config parameter without warning. It seems there is no checking for valid parameters.

Using python driver 1.5.2

**Comment by zhenlineo** [comment]
Hi @mjmare,

Short story:
If you cannot control when the server and client starts in your environment, then I would recommend you to add the following code into your client startup:

```
def wait_for_server(host, port, timeout=10):
    port = port or 7474
    running = False
    t = 0
    while not running and t < timeout:
        try:
            s = create_simple_connection((host, port)) # or try to create a driver
        except IOError:
            sleep(1)
            t += 1
        else:
            s.close()
            running = True

    if not running:
        raise RuntimeError("Server %s:%d did not become available in %d seconds" % (host, port, timeout))
```

Long story:

Before the server starts, the port is not open for connecting. The driver's attempt to create connection will be immediately rejected. In this case, a connection dose not even get started. The `connection_timeout` will only be honored if your connection is connected but not yet fully finished to create (due to some high load in your server). For more details explanation, you probably need to read more about TCP and OS about how they handle sockets.

I verified that the config parameter `connection_timeout` is passed down correctly in the code. There is some checks for certain config parameters such as encryption config. But it only happens near the place where they are used in the code. We will take your suggestion to valid them as earlier as possible in future driver versions.

Thanks again.
Zhen

**Comment by mjmare** [comment]
Thanks Zhen for the prompt and extensive reply. May I suggest that the docs for the connection_timeout param be augmented to include your explanation? 

I have currently worked around the issue by not creating the driver at app startup (as suggested in the docs) but by creating the driver lazily (ie at first request).
