### ISSUE TITLE
Neo4j connectivity authentication error

### ISSUE THREAD

**Issue by Shashank200** [neo4j/neo4j-python-driver#242]
Trying to develop flask search web app with neo4j.I am using py2neo version 2.0.8 and trying to connect with neo4j updated version 3.4,
The problem is driver connection error.I think it's compatibility error.Could you provide driver for connecting py2neo 2.0.8 with neo4j.i have to use only py2neo 2.0.8,because my code is compatible with that version.

**Comment by technige** [comment]
Hi @Shashank200 

This is the repository for the official Python driver, not py2neo. These are different projects.

However, I'm also the author of py2neo so can answer the question. Py2neo 2.0.8 was released almost three years ago, long before Neo4j 3.4, so the two are unlikely to be compatible. You'll either have to use an older version of Neo4j or upgrade py2neo. I heavily recommend the latter as otherwise you will be using two old, unsupported pieces of software.
