### ISSUE TITLE
Getting error - ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 61)

### ISSUE THREAD

**Issue by tstreamDOTh** [neo4j/neo4j-python-driver#251]
I tried to run the example given for python at https://neo4j.com/developer/
I get the following error

---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/neo4j/bolt/connection.py in _connect(resolved_address, **config)
    577         log_debug("~~ [CONNECT] %s", resolved_address)
--> 578         s.connect(resolved_address)
    579         s.settimeout(t)

ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

ServiceUnavailable                        Traceback (most recent call last)
<ipython-input-9-56662974c754> in <module>()
      1 from neo4j.v1 import GraphDatabase, basic_auth
      2 
----> 3 session = GraphDatabase.driver("bolt://localhost", auth=basic_auth("neo4j", "<password>")).session()
      4 
      5 # Insert data

/usr/local/lib/python3.7/site-packages/neo4j/v1/api.py in driver(cls, uri, **config)
     86         :class:`.Driver` subclass instance directly.
     87         """
---> 88         return Driver(uri, **config)
     89 
     90 

/usr/local/lib/python3.7/site-packages/neo4j/v1/api.py in __new__(cls, uri, **config)
    125         for subclass in Driver.__subclasses__():
    126             if parsed.scheme == subclass.uri_scheme:
--> 127                 return subclass(uri, **config)
    128         raise ValueError("URI scheme %r not supported" % parsed.scheme)
    129 

/usr/local/lib/python3.7/site-packages/neo4j/v1/direct.py in __new__(cls, uri, **config)
     71 
     72         pool = DirectConnectionPool(connector, instance.address, **config)
---> 73         pool.release(pool.acquire())
     74         instance._pool = pool
     75         instance._max_retry_time = config.get("max_retry_time", default_config["max_retry_time"])

/usr/local/lib/python3.7/site-packages/neo4j/v1/direct.py in acquire(self, access_mode)
     42 
     43     def acquire(self, access_mode=None):
---> 44         return self.acquire_direct(self.address)
     45 
     46 

/usr/local/lib/python3.7/site-packages/neo4j/bolt/connection.py in acquire_direct(self, address)
    451                 if can_create_new_connection:
    452                     try:
--> 453                         connection = self.connector(address, self.connection_error_handler)
    454                     except ServiceUnavailable:
    455                         self.remove(address)

/usr/local/lib/python3.7/site-packages/neo4j/v1/direct.py in connector(address, error_handler)
     68 
     69         def connector(address, error_handler):
---> 70             return connect(address, security_plan.ssl_context, error_handler, **config)
     71 
     72         pool = DirectConnectionPool(connector, instance.address, **config)

/usr/local/lib/python3.7/site-packages/neo4j/bolt/connection.py in connect(address, ssl_context, error_handler, **config)
    705         raise ServiceUnavailable("Failed to resolve addresses for %s" % address)
    706     else:
--> 707         raise last_error

/usr/local/lib/python3.7/site-packages/neo4j/bolt/connection.py in connect(address, ssl_context, error_handler, **config)
    695         log_debug("~~ [RESOLVED] %s -> %s", address, resolved_address)
    696         try:
--> 697             s = _connect(resolved_address, **config)
    698             s, der_encoded_server_certificate = _secure(s, address[0], ssl_context, **config)
    699             connection = _handshake(s, resolved_address, der_encoded_server_certificate, error_handler, **config)

/usr/local/lib/python3.7/site-packages/neo4j/bolt/connection.py in _connect(resolved_address, **config)
    585         _force_close(s)
    586         if error.errno in (61, 99, 111, 10061):
--> 587             raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error.errno))
    588         else:
    589             raise

ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 61)

**Comment by technige** [comment]
Looks like a network configuration problem, but impossible to know without more information. Suggest you try establishing a raw TCP connection to your server with, say, `netcat` and see what that reports.

**Comment by theoptips** [comment]
Have the same issue would like to track it. Specifically when using py2neo. Error appears after
from py2neo import Graph
graph = Graph()
graph object could not be initialized

also tried with neo4j.v1 GraphDatabase
same error
from neo4j.v1 import GraphDatabase
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j","password"))

also tried pip install upgrade neo4j 
new neo4j python driver
https://github.com/neo4j/neo4j-python-driver
from neo4j import GraphDatabase

driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))

Same error
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7474) (reason 61)

tried a few things on stackoverflow too including modifying localhost didn't work

**Comment by andrewbain** [comment]
I am having the same error, but only when I try to run the code in a docker container. Did you solve this?

**Comment by ghost** [comment]
I have received this issue this issue also while using the official neo4j driver for python ServiceUnavailable "Failed to establish connection to ('172.31.62.146', 7687) (reason 111)

**Comment by ghost** [comment]
I think that these errors can be the result of not properly managing driver sessions, make sure you close the driver session after you have performed your transaction, otherwise they will overload the server!

**Comment by technige** [comment]
The error message in the subject line of this issue shows a general failure to connect at TCP level. There could be any number of reasons behind this, often linked to the network infrastructure or other system setup.

To that end, it's likely that the separate posts here are talking about a range of issues. Additionally, without further detail about physical network setups and server topologies, plus a description of how we might recreate the error back at Neo4j, we're probably unlikely to make much progress on working through these.

I'm going to leave this thread open for more detail to be added. For something to be actionable, please provide as much detail as possible about how we can simulate the same conditions for testing. Also include version information, stack traces and any snippets of code (not full modules, please) that trigger errors.

One helpful diagnostic tip is to use a command line tool such as `telnet` or `nc` to try to establish a simple TCP connection from the client to the server on the host and port on which Bolt should be available (e.g. `nc localhost 7687`). If this fails to connect, then the problem is with your network or server configuration, not your driver or client application.

**Comment by youdar** [comment]
I had the same issue:

> from py2neo import Graph
> g = Graph()

Gave error

What worked for me was
`g = Graph('http://localhost:7474/')` .  
I use Python 3.6 with py2neo 4.1.0

**Comment by velhari** [comment]
You should uncomment this config from neo4j.conf file to work

 To accept non-local connections, uncomment this line:
#dbms.connectors.default_listen_address=0.0.0.0

**Comment by youdar** [comment]
But this is a local connection, why do we need to accept non-local connections ?

**Comment by technige** [comment]
There have been several mentions of port 7474 on this thread. Note that this is the default HTTP port, **not** the Bolt port.

The official drivers only support Bolt, although py2neo also supports HTTP. If you are using py2neo, please raise an issue on that repository instead.

**Comment by technige** [comment]
Unfortunately, we aren't generally able to diagnose individual connection issues since these will often be due to local configuration or network idiosyncrasies. Also, this is the repository for the official Bolt driver so, as such, we can't deal with any HTTP issues (port 7474) or issues with py2neo here.

For anyone having similar issues, I suggest looking at this post on our community forum:
https://community.neo4j.com/t/troubleshooting-connection-issues-to-neo4j/129

If that doesn't help, and you've exhausted your local diagnostics, post a separate issue there detailing as much as you can about your driver and server configuration, your network topology, and what you've tried (e.g. `nc` from command line to test raw TCP connections).
