### ISSUE TITLE
Docs for temporal data types inaccurate

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#256]
https://neo4j.com/docs/api/python-driver/current/types/temporal.html suggests that a Cypher Date is mapped to a standard datetime.date, whereas in actuality it is mapped to a neotime.Date.
The neotime.Date has no provisions to be cast as a standard date AFAICT.

Standard date(time)s would make interoperability much more convenient.

**Comment by technige** [comment]
The mappings are explained in the paragraph above the table:

> The table below shows the general mappings between Cypher and the temporal types provided by the driver. In addition, the built-in temporal types can be passed as parameters and will be mapped appropriately.

As explained here, the driver provides temporal types to which Cypher temporal values from query results are mapped. These are the `neotime.*` classes that you see. The built-in types are also listed because, as stated, these can be used for parameter values and will be coerced accordingly.

The built-in types cannot be used for results since Cypher operates on nanosecond precision whereas Python's types support only microsecond precision. Using these types would therefore lead to lossy results.

**Comment by mjmare** [comment]
I just noticed that the only mention of "neotime" on that page is a link to the package. 
I think the Table would benefit from a column with the neotime classes (+link). The neotime classes would benefit from convenience methods to convert to standard temporal classes.
