### ISSUE TITLE
Bump the major version between 1.5.3 and 1.7.0 due to backward compatibility break

### ISSUE THREAD

**Issue by chiffa** [neo4j/neo4j-python-driver#265]
Prior code retrieving properties from neo4j node instances 
`` node.properties['property_name']`` fails with the 1.7.0 version, due to the fact that ``properties`` was renamed to ``_properties``. 

This is a backward compatibility-breaking change and as per [semantic version spec #8 ](https://semver.org/#spec-item-8) has to be accompanied by a major version bump.

Please release a patch to support legacy behavior or bump the major version.

**Comment by technige** [comment]
Hi @chiffa 

The `node.properties` attribute was never a documented part of the API. The correct way to access properties has always been `node[key]` or `node.get(key, default)` since nodes are dictionary-like.

The change you identify was to internalise the attribute with a leading underscore, and is consistent with the [PEP8](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces) stance on undocumented interfaces:

> Documented interfaces are considered public, unless the documentation explicitly declares them to be provisional or internal interfaces exempt from the usual backwards compatibility guarantees. All undocumented interfaces should be assumed to be internal.

**Comment by chiffa** [comment]
Hi @technige,

I am aware of PEP8 and completely support its usage. However, as of the 1.5.3 (the version I used in my app), the lack of the documentation of the preferred properties access mode in the [wiki/doc](https://github.com/neo4j/neo4j-python-driver/wiki). Given the properties usage was not underscored nor raised a warning upon use I believe their usage was a fair use. 

Or maybe I am missing a documentation item?
