### ISSUE TITLE
Underlying Socket connection Gone error with Vesion  1.7.4 and Neo4j 3.5

### ISSUE THREAD

**Issue by YaphetKG** [neo4j/neo4j-python-driver#293]
Hi,

I was doing a fresh install of a neo4j - python code. And I have downloaded the latest neo4j docker image. along side it I have neo4j driver version 1.7.4, 

So my code connects well with
```
from neo4j import GraphDatabase
driver = GraphDatabase.driver(uri="bolt://host:7687', auth=('neo4j','XXXX'))

# as soon as I do the following code I get this error.
# Failed to write data to connection Address(host='xxx', port=xxx) (Address(host='xxx', port=xxxx)); ("0; 'Underlying socket connection gone (_ssl.c:2061)'")
with driver.session() as session:
    session.run('match (c) return c ')

```

So as a fix I downgraded my driver to version 1.7.2 and its working well.

**Comment by Asmeble** [comment]
Maybe try capitalizing the sql3 calls...?

**Comment by YaphetKG** [comment]
@Asmeble  I don't think that is the issue here

**Comment by p-sodmann** [comment]
I am also getting the Error after updating everything to the latest version: ("0; 'Underlying socket connection gone (_ssl.c:2067)'")  
Downgrading to 1.7.2 did not solve the issue for me.

EDIT:
It is an issue with Neobolt, I did not try every version, but Neobolt 1.7.4 works with neo4j-python 1.7.4 which is funny since the version numbers are not correlated.

**Comment by nandosola** [comment]
This combination works for me with Neo4j-community 3.5.8:
```
neo4j==1.7.2
  - neobolt [required: >=1.7.4,<2, installed: 1.7.9]
  - neotime [required: >=1.7.1,<2, installed: 1.7.4]
    - pytz [required: Any, installed: 2019.1]
    - six [required: Any, installed: 1.12.0]
```

Versions from 1.7.3 require NeoBolt to be >= 1.7.12, which triggers this issue…

**Comment by ali-ince** [comment]
Latest neobolt contains the fix and the dependencies should be updated with driver.

**Comment by bratushka** [comment]
@ali-ince sorry to raise this again, but the combination
```
neo4j==1.7.4
neobolt==1.7.13
neotime==1.7.4
```
on Windows produces this error:
```
Failed to write data to connection Address(host='neo', port=7687) (Address(host='172.18.0.3', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2263)'")
```
Docker Engine - Community (19.03.2)
Windows 10 1903 (build 18362.356)

Combination of
```
neo4j==1.7.2
neobolt==1.7.9
neotime==1.7.4
```
works just fine

**Comment by martin-neotech** [comment]
What python version are you using?

```python
from neo4j import GraphDatabase

if __name__ == "__main__":

    driver = GraphDatabase.driver(uri="bolt://localhost:7687", auth=("neo4j","word"))
    with driver.session() as session:
        result = session.run("match (c) return c")
        result = list(result)
        print("rows: {}".format(len(result)))

    #python --version
    #Python 3.7.4

    #python -m pip freeze
    #neo4j==1.7.4
    #neobolt==1.7.13
    #neotime==1.7.4
```

```
>[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```

Works fine

**Comment by bratushka** [comment]
@martin-neotech Python 3.7.3

**Comment by Nirusu** [comment]
@ali-ince 
> Latest neobolt contains the fix and the dependencies should be updated with driver.

Eh, I'm not really sure. I'm coming from [this issue](https://github.com/neo4j-contrib/neomodel/issues/474) here and got this issue just by installing neomodel via pip3 and running neo4j 3.5.11.

Reinstalled all these specific with the most recent versions in PyPi, yet they're causing this issue:

```
➜  neomodel_test git:(master) ✗ pip3 install neo4j neo4j-driver neobolt pytz neomodel --no-cache-dir
Collecting neo4j
  Downloading https://files.pythonhosted.org/packages/ed/a9/248314080b0f875facf898fb270e99024a3d47edf4cdb01c87ff9c447151/neo4j-1.7.5.tar.gz
Collecting neo4j-driver
  Downloading https://files.pythonhosted.org/packages/ae/36/531d7ffa03d0895cf52e446c6f11c764a914ca6bef69b9657def68d656d4/neo4j-driver-1.7.5.tar.gz
Collecting neobolt
  Downloading https://files.pythonhosted.org/packages/9f/63/bb8b2ba18b4929c8bd17299d499530d6779635439e33bcc95043dc597223/neobolt-1.7.15.tar.gz (183kB)
    100% |████████████████████████████████| 184kB 7.3MB/s 
Collecting pytz
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 7.1MB/s 
Collecting neomodel
  Downloading https://files.pythonhosted.org/packages/63/27/7e967bd553c6bae8586237f89e7018865e5c7c86fa576cbbbb2f8f13e2b4/neomodel-3.3.2.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 12.1MB/s 
Collecting neotime~=1.7.1 (from neo4j)
  Downloading https://files.pythonhosted.org/packages/0b/7e/ca368a8d8e288be1352d4e2df35da1e01f8aaffbf526695df71630bcb8a6/neotime-1.7.4.tar.gz
Collecting six (from neotime~=1.7.1->neo4j)
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: 
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: neobolt, pytz, six, neotime, neo4j, neo4j-driver, neomodel
  Running setup.py install for neobolt ... done
  Running setup.py install for neotime ... done
  Running setup.py install for neo4j ... done
  Running setup.py install for neo4j-driver ... done
  Running setup.py install for neomodel ... done
Successfully installed neo4j-1.7.5 neo4j-driver-1.7.5 neobolt-1.7.15 neomodel-3.3.2 neotime-1.7.4 pytz-2019.3 six-1.12.0
➜  neomodel_test git:(master) ✗ python3 test.py                                                     
Failed to write data to connection Address(host='localhost', port=7687) (Address(host='127.0.0.1', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2084)'")
Failed to write data to connection Address(host='localhost', port=7687) (Address(host='127.0.0.1', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2084)'")
```

Now, someone back in the issue I filed for neomodel mentioned that going back to older version helps, and I confirm that. What I also can confirm is, that downgrading Neo4j to the latest 3.4 release version also fixes this issues.
Also, I tried a couple of versions of each package and then proceeded to install the latest versions, with also suddenly made the issue disappear? But then after uninstalling and reinstalling the packages again, the issue is back.

My Terminal history can be found here. It's a bit messy, but maybe there's useful information in there?:
https://gist.github.com/Nirusu/56da4f626d17645d12a9b3348d3563a1

But overall, this is a strange issue, especially since some people reported that didn't upgrade or downgrade anything. Seems like this triggers only in a specific, yet not so uncommon case?

**Comment by dkloving** [comment]
I encountered this issue after installing neomodel and letting pipenv handle the dependencies. It grabbed neobolt 1.7.15. After downgrading neobolt to 1.7.9 everything works.
