### ISSUE TITLE
Connection closed after few minutes: defunct connection Address

### ISSUE THREAD

**Issue by carmignanivittorio** [neo4j/neo4j-python-driver#316]
Hi,
I have a server in which the connection is opened (python):

    self._driver: Driver = GraphDatabase.driver(credentials["uri"], auth=(credentials["user"], credentials["password"]), max_connection_lifetime=3600*24*30, keep_alive=True)
I run some requests and it works all perfectly. The requests are run by using the function:

```
def __exe_query(self, query: str):
    with self._driver.session() as session:
        session.run(query).consume()
```
Despite these queries do not return anything relevant I added .consume() based on this post [Error while loading data in Neo4j (Python Driver)](https://community.neo4j.com/t/error-while-loading-data-in-neo4j-python-driver/7413/9).

I wait 4-5 minutes (while the server is running waiting for other requests), I run the exact same requests, and I get the **error**:

`"Failed to read from defunct connection Address(host='****', port=**)"`

I also tried with `max_connection_lifetime=-1`.

I am working with python 3.7.0 with these libraries versions: neo4j==1.7.2 neobolt==1.7.9 neotime==1.7.4 as suggested by https://github.com/neo4j/neo4j-python-driver/issues/293.
It does not work in Win10 and Linux Ubuntu 18.04.3 LTS.

Thanks for your help and attention,
Vittorio

**Comment by technige** [comment]
Hi @carmignanivittorio

There is nothing fundamentally wrong with your code here. However, I think you may have misunderstood the purpose of the `max_connection_lifetime` setting.

In some network infrastructures (for example AWS) there is a network component that will attempt to shut down what it considers to be idle connections. I assume you are using such an infrastructure.

These shutdowns typically occur after a few minutes of perceived inactivity, and in the case of AWS, the TCP Keep-Alive mechanism (which you have enabled via `keep_alive=True`) has no effect. This is because AWS chooses to _only_ see data packets as contributing to the liveness of the connection.

The `max_connection_lifetime` setting was introduced so as to allow the driver to gracefully pre-empt the AWS shutdowns, and as such should be set to _slightly less_ than the AWS idle time (e.g. 55 seconds vs the AWS default of 60 seconds). This will ensure that connections obtained from the pool are not so old as to expire by the AWS mechanism. Connections shutdown gracefully by the driver should not become defunct; you should therefore not see this error.

This setting **does not** force the connection to stay open. The driver has no control over the AWS shutdown mechanism.

For more information on this mechanism:
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html

Hope this helps.
