### ISSUE TITLE
[Feature Request] Deprecate pytz

### ISSUE THREAD

**Issue by JVemmer** [neo4j/neo4j-python-driver#610]
The driver currently relies on a pytz implementation of datetime. However, pytz is facing gradual deprecation across the Python landscape, and currently the Python driver for Neo4j does not appear to support anything other than a pytz implementation; at the very least, it should support both pytz and the dateutil/zoneinfo approach.
I made a small test, using the latest version of the driver, with the latest Neo4j community edition 4.3, creating a node with two different datetime implementations, and Neo4j handled them very differently. The test is very simple, it takes a datetime in string format, and transforms that into datetimes via either option (datetime + pytz or dateutil), and then creates a node that has both datetimes as properties.
Python code:
```
import pytz
from datetime import datetime
from dateutil import parser
from neo4j import GraphDatabase

timestamp = "2017-07-20T01:29:00Z"
uri = "neo4j://localhost:7687"
p_dt = datetime.strptime(timestamp, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=pytz.utc) # Returns datetime.datetime(2017, 7, 20, 1, 29, tzinfo=<UTC>)
d_dt = parser.isoparse(timestamp) # Returns datetime.datetime(2017, 7, 20, 1, 29, tzinfo=tzutc())
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def create_test_node(tx, pytz_datetime, dateutil_datetime):
    tx.run("CREATE (n:Test) "
           "SET n.pytz_datetime = $pytz_datetime, n.dateutil_datetime = $dateutil_datetime "
		   "RETURN n",
           pytz_datetime=pytz_datetime, dateutil_datetime=dateutil_datetime)

with driver.session() as session:
    session.write_transaction(create_test_node, p_dt, d_dt)

driver.close()
```
Going into the Neo4j browser, and looking at the node, the following is returned:
```
{
    "identity": 54,
    "labels": [
        "Test"
    ],
    "properties": {
        "pytz_datetime": "2017-07-20T01:29:00.0[UTC]",
        "dateutil_datetime": "2017-07-20T01:29:00Z"
    }
}
```
So there is very clearly different handling, depending on whether or not the datetime utilizes pytz-based timezones or not.

For more information regarding the deprecation of pytz, here is a collection of various links that talks about it:
- [https://discuss.python.org/t/pep-615-support-for-the-iana-time-zone-database-in-the-standard-library/3468/16](https://discuss.python.org/t/pep-615-support-for-the-iana-time-zone-database-in-the-standard-library/3468/16) this is the author of pytz himself talking about him looking forward to deprecating pytz.
- [https://github.com/pganssle/pytz-deprecation-shim](https://github.com/pganssle/pytz-deprecation-shim) the pytz deprecation shim library.
- [https://docs.djangoproject.com/en/dev/releases/4.0/#whats-new-4-0](https://docs.djangoproject.com/en/dev/releases/4.0/#whats-new-4-0) Django webframework deprecating pytz.
- [https://fedoraproject.org/wiki/Changes/DeprecatePytz](https://fedoraproject.org/wiki/Changes/DeprecatePytz) Fedora announcing the deprecation of pytz.

**Comment by robsdedude** [comment]
I've looked long and extensively into this issue. There is not way for us to deprecate `pytz` at this point because `zoneinfo` does not play nicely with custom `datetime` implementations which this driver relies upon as we're adding nanosecond precision support. This might change in the future https://bugs.python.org/issue15443 :eyes:. Until then there is little we can do about removing `pytz` as a dependency.
However, I'll keep this issue open, because the driver could and should support at least serializing `datetime`s with `zoneinfo` time zones. But deserialization is just not possible with `zoneinfo`'s time zone implementation as explained above.

Finally, about this specific example you gave: first, let's establish that there are two ways of storing a datetime (same for times) in Neo4j. They come from Java land: such with a fixed UTC offset (e.g., `+01:30`) which I'll call `Neo4jDateTime` here and those with a IANA zone id (e.g., `"Europe/Stockholm"`) which I'll call `Neo4jDateTimeZoneId` for this explanation. (Side note: ofc. there are also datetimes/times without any time zone information, but they are irrelevant for this.)

Now if you use `pytz`'s time zones, we can gather the a time zone ID from `.zone` (which does not exist for `pytz.FixedOffset`). For `pytz.UTC` this, `.zone` is `"UTC"`. So the driver stores the `p_dt` for your example as `Neo4jDateTimeZoneId`. If you, in contrast, use `dateutil`, which only supports fixed UTC offset time zones and has no concept of zone IDs, the driver has to rely on storing the `d_dt` as `Neo4jDateTime`. So you end up with two different types in the DB that represent the same thing.
