### ISSUE TITLE
verify_connectivity() fails with async api

### ISSUE THREAD

**Issue by kthr** [neo4j/neo4j-python-driver#721]
Error in verify_connectivity of async api

**Neo4j Version:** 4.4.3 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Python driver 5.0.0a1
**Operating System:** MacOS

### Steps to reproduce
1. Start Neo4j instance on localhost with credentials neo4j:password
2. Run query below 
```
import asyncio
import neo4j

driver = neo4j.AsyncGraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
asyncio.run(driver.verify_connectivity())
```
### Expected behavior
No exception or DriverError
### Actual behavior
Throws AttributeError
*Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<env>/apothera/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "<env>/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "<env>/lib/python3.10/site-packages/neo4j/_async/driver.py", line 312, in verify_connectivity
    value = await result.single().value()
AttributeError: 'coroutine' object has no attribute 'value'*

**Comment by robsdedude** [comment]
Hello and thank you very much for the bug report. I've tested `verify_connectivity` with version 5.0.0a1 and was able to reproduce the error you encountered (only for connections with `bolt://` URIs, `neo4j://` works fine with that version). I've then tested the same code against the current 5.0 branch (in development) and due to some internal changes to what `verify_connectivity` does, this bug is already fixed for the upcoming 5.0 release.

If you encounter more issues with the async driver, we are more than happy to hear about it so that we can improve it.
