### ISSUE TITLE
[typing] neo4j/_async/work/transaction.py's `AsyncTransaction.run` returns a `neo4j.AsyncResult`

### ISSUE THREAD

**Issue by endafarrell** [neo4j/neo4j-python-driver#770]
I've been using the async driver via `pip install neo4j==5.0.0a1` and noticed a type hint error.

[typing] neo4j/_async/work/transaction.py's `AsyncTransaction.run` returns a `neo4j.AsyncResult`, not a `neo4j.Result`

It looks like line 109 should change from:

         :rtype: :class:`neo4j.Result` 

to

         :rtype: :class:`neo4j.AsyncResult`

**Comment by robsdedude** [comment]
Hi @endafarrell and thanks a lot for reaching out.

Good catch there. For the next 5.0 alpha release, which will not be an async preview release but contain the actual 5.0 changes (probably coming in September), this has already been fixed in e74c6f1a15fa6a8e690be46321c4eb84afa45d46 (https://github.com/neo4j/neo4j-python-driver/pull/658/files#diff-e01d8571ae2f3bce8355a427ad185a4f087a6763e98d95438f0cef6466621b51R103-R106) and then converted to type annotations in 799720d58a167423c35bafc1aa708b2b84a368a0 (https://github.com/neo4j/neo4j-python-driver/pull/767/files#diff-e01d8571ae2f3bce8355a427ad185a4f087a6763e98d95438f0cef6466621b51R94-R99).

If you spot more, I'm always happy to receive feedback, especially regarding the async driver.
