### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#78]
Please improve the docs by:
- providing API docs (more precise than http://neo4j.com/docs/developer-manual/current/#driver-manual-index) with respect to parameter and result descriptions and types
- providing links to narrative docs and API docs on the GH page.
- put the docs on readthedocs which is familiar to python users.

Thanks!

**Comment by zhenlineo** [comment]
We added the links to such docs in [wiki](https://github.com/neo4j/neo4j-python-driver/wiki)
Also a simple line to direct users to find wiki from the GH readme page.

We would like to host the docs ourselves, so no plan to put any docs on readthedocs for now.

Please let us know if you still find it is hard to search docs for this driver.

**Comment by offero** [comment]
The docs on providing statement parameters could be improved. For example, I don't know if I have to provide each value individually, or if I can create a single {properties} key that can be replaced by all the properties I have in an object.

Public facing function and class docs could include descriptions of input/output and examples. Some do, but I still find myself having to read other docs/code to figure out how to properly call things.

Also, I'm not sure when and if I'm supposed to call consume(). I had a script that was importing data and I ran it a bunch of times but it didn't import anything. I think it was because either I didn't call consume() after each call to session.run() or I didn't close the session properly so that it could execute. The problem was that I just didn't know what was happening within these functions from the documentation I had available.

**Comment by zhenlineo** [comment]
Sorry for the weak docs now. We will improve it to cover all you questions.

Just a quick answer for your @offero doubts about consume(): 

The driver is designed to lazily run. That is to say `result = session.run()` will not run your statement, but `result.next()` (iteration on result) will send the statement to the server, run the statement and stream the result back to you.

If your statement dose not have a return, then you need to call `session.run().consume()` to enforce the statement to run. If your statement has a return, then iterating on your returned result will automatically consume, therefore you do not need to call `consume`.  

So the key is **always consume your result**, either by iterating on the result directly or call `consume()`. Another important note, to save your memory usage, only pull the results that you needed back.

Then finally about `close`. When you do close, everything will be cleaned for this session. If you have not run, nothing will be run. If you have not used the result, no result will be available anymore.

**Comment by mjmare** [comment]
Thx for the clarification. This will be added to he docs, I presume?

The docs for .close() need special attention especially in the context of transactions. I have run into problems with commit/rollback and whether or not to close.

**Comment by svidela** [comment]
I'd like to add a comment about docs. I noted that both, Session and Transaction objects implement `__enter__` and `__exit__` methods but the docs only mention the possibility of using the `with` block for Transaction (http://neo4j.com/docs/api/python-driver/beta/#neo4j.v1.Transaction). Is there any reason not to use the `with` block for a session?. Or is it just fine to use:

```
 with driver.session() as session:
     pass
```

In fact, I'm using it already and everything seems to work just fine. But it would be nice to have it documented and be sure that it's part of the stable API.

**Comment by technige** [comment]
Thanks for all these suggestions, we are looking at the docs over the next few weeks and will deliver improved documentation with the 1.1 series drivers.
