### ISSUE TITLE
Async driver removing connection twice from pool 

### ISSUE THREAD

**Issue by Dz0n1Pr0** [neo4j/neo4j-python-driver#785]
I encountered the same issue and the same error output as in https://github.com/neo4j/neo4j-python-driver/pull/598
The error states: ValueError: deque.remove(x): x not in deque

The Neo4j Version that we are using is 4.4.3 Community edition running as a single instance. 
We are using the experimental driver version 5.0.0a1, so we expected that there might be slight issues like these but we are hoping this can get fixed. 

It doesn't happen every time we send a few requests at the same time, but occasionally this happens and we don't get an expected response back but the error message instead.

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

This is in fact the exact same bug. 5.0.0a1 got cut off from 4.4.1. That's why the fix for this issue (released with 4.4.4) is not part of the preview release. However, the fix also got merged into 5.0 https://github.com/neo4j/neo4j-python-driver/pull/732. So it will be part of the next 5.0 release (5.0.0a2) which should go out very soon.

I'll close this issue as it's already fixed (but unreleased). Please feel free to keep commenting if you have further questions or to re-open it, should the bug turn out to still be present in 5.0.0a2.
