### ISSUE TITLE
No network-based error on session.run()

### ISSUE THREAD

**Issue by L4in** [neo4j/neo4j-python-driver#82]
I'm using the driver version 1.0.0, installed from pip on Ubuntu 15.10.
I want the session to be open for more than mere seconds, thus I'm concerned about a specific case where the database is live during the

```
         try:
            session = driver.session()
        except ProtocolError:
            print("Cannot connect to neo4j. Aborting.")
```

but not during the subsequent `session.run(string)` with string as the formatted CYPHER request.
Thus, I would like to make sure that I detect any session-level error, and exit or try to fix the issue depending of its nature.

By manually starting the database, executing the `self.session = driver.session()`, then shutting down the database and calling the `session.run(string)` does not yield any error.

However, `ProtocolError` is thrown on `session.close()`.

It doesn't seem logic for those two network-based functions to have `ProtocolError` thrown and not for `session.run`.

With this current system, I cannot tell if a communication error appeared until I choose to close the session. As I want the session open for quite a long time, opening and closing the session for each run doesn't seem like a very good option.

**Comment by technige** [comment]
This behaviour occurs because `session.run` is lazy. That is, no network activity occurs until you begin to consume the result. This allows for more efficient network usage by bundling multiple requests into fewer network packets whenever possible.

You therefore do not need to close the session, merely consume the result by iterating through the records or using `result.consume()`.
