### ISSUE TITLE
Port 7687 no longer connects

### ISSUE THREAD

**Issue by andyhegedus** [neo4j/neo4j-python-driver#857]
Hi,
After upgrading to version 5, I can no longer connect to the database via port 7687 as is shown in your documentation.
I also notice that the Desktop browser no longer uses that port

Version	4.4.8
Edition	enterprise
Status	Active
IP address	localhost
Bolt port	11003 
HTTP port	11004 
HTTPS port	7473 

In my python scripts I need to change the port to 11003 to see the database.
Also Bloom no longer sees the open database and I am guessing it is using port 7687.
Andy

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

Since this is not per-se a driver issue but a database/network configuration issue, the generally right place to ask are our [community forums](https://community.neo4j.com/) where you'll also find help from more people than just the driver maintainers.

Two things pop out here to me:
 * Neo4j browser is by default running on port 7474 not 7687
 * I don't know where you copy pasted the database information from, but it says

   > Bolt port 11003
   
   With Bolt being the binary protocol the driver uses to communicate with the DMBS. So it's no surprise you have to point the driver to that port. Now for *why* your server is listening on that port... Not sure. Check your config, seek for help in the forums. By default, Neo4j (also 5.x) listens on port 7687 for bolt connections.
   
I will close this issue as it's not directly a driver problem or something that needs fixing. Feel free to keep commenting, though.
