### ISSUE TITLE
Cannot use Session.run with str (Type Hint Mistake)

### ISSUE THREAD

**Issue by stringthread** [neo4j/neo4j-python-driver#876]
# Bug Report
Hello.
In type check, neo4j.Session.run() and neo4j.AsyncSession.run() reject the first argument `query` of `str` type.
This issue occurs on type checking process, not on runtime.
(I'm using pylance v2022.12.20 as type checking tool.)

## Error message ( in vscode + pylance )
> Argument of type "str" cannot be assigned to parameter "query" of type "LiteralString | Query" in function "run"
>   Type "str" cannot be assigned to type "LiteralString | Query"
>     "str" is incompatible with "LiteralString"
>     "str" is incompatible with "Query"
> Pylance [reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)

## Reproduction
```python
from neo4j import GraphDatabase

uri = "neo4j://example.com:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))
def run(query:str):
    with driver.session() as session:
        session.run(query)  # Type Error Occurs Here
```

## Cause
At [src/neo4j/_sync/work/session.py@L236](https://github.com/neo4j/neo4j-python-driver/blob/5.3.0/src/neo4j/_sync/work/session.py#L236), type of query is defined as `t.Union[te.LiteralString, Query]`, which excludes usual `str` types. ( Just the same in AsyncSession: [src/neo4j/_async/work/session.py@L236](https://github.com/neo4j/neo4j-python-driver/blob/5.3.0/src/neo4j/_async/work/session.py#L236) )

## Additional Question: is this issue introduced in purpose?
In prior version ( I checked 5.2.1 ) , the argument `query` of `Session.run` was typed as `t.Union[str, Query]`, and I could use `str` typed arguments without type errors.
This fact suggests that the issue might be introduced in purpose.
I will create a pull request for this issue tomorrow, but I'm not certain if it is ok to solve this issue.
If this issue was introduced in purpose, please tell me the reason `Session.run` should reject non-literal string types.

# My Environment
Python Version: Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Driver Version: 5.3.0
Server Version and Edition: Not matters, since this issue is type checking error
Operating System: Windows 10 Home Edition
Type Checking Tool: pylance v2022.12.20 ( with Visual Studio Code 1.73.1 )

**Comment by robsdedude** [comment]
Thank you for reaching out.

As you suspected, this was very much intentional. It's meant to help users spot potential query injection vulnerabilities in their code.
See also [PEP675](https://peps.python.org/pep-0675/) where this type hint was introduced exactly for that purpose. I also mentioned the change [here](https://github.com/neo4j/neo4j-python-driver/blob/5.0/CHANGELOG.md#version-53) but forgot to copy it over to the changelog in the wiki. I'll fix that asap.

Ideally, you don't pass dynamically generated query strings to any database driver at all. However, in Neo4j, there are legitimate use-cases where this is necessary (see [this example](https://neo4j.com/docs/python-manual/current/query-advanced/#_dynamic_values_in_property_keys_relationship_types_and_labels)). For those cases, you can still tell your type checker to ignore those (hopefully few) cases after you've double and tripple checked that your code is safe.

So please don't spend time on crafting a PR (at least not without further discussion).

I'll close the issue as I don't see the need to act here. But please feel free to keep discussing.

**Comment by stringthread** [comment]
Thank you for your answer!
I support your choice that we use `te.LiteralString` by default, and use casting for few exceptional cases.
